### ISSUE TITLE
[Feature Request] Workflow is static object, not unit testable

### ISSUE THREAD

**Issue by rsr-maersk** [temporalio/sdk-dotnet#182]
Thanks for the great package

### Is your feature request related to a problem? Please describe.

We cannot do true TTD / unit testing with the current SDK. 
The SDK looks much like ASP.NET classic with the static HttpContext. However it should be more like minimal APIs exposing a context and SP.

### Describe the solution you'd like

Noting static in SDK. 
Everything instanced as abstractions or interfaces

**Comment by cretz** [comment]
This is very much intentional. We do this on purpose in order to disallow mocking/inheriting. Workflow environments are a lot of things about them that makes mocking/inheriting in a normal context way not feasible, you'll need the same static-class logic. See https://github.com/temporalio/sdk-dotnet/#workflow-testing for more information about testing.

Also, feel free to join us on `#dotnet-sdk` channel on https://t.mp/slack or on the forums at https://community.temporal.io/.

(closing as not an issue, but feel free to continue adding comments or joining us in one of the places above)

**Comment by rsr-maersk** [comment]
@cretz mate, "This is very much intentional. We do this on purpose in order to disallow mocking/inheriting".
This doesn't make sence and goes against years of software pronciples and also TDD.

This is a flaw in your design, sorry mate

**Comment by cretz** [comment]
Here is the proposal section with the results of the design discussion amongst many developers: https://github.com/temporalio/proposals/blob/master/dotnet/sdk-phase-2.md#workflow-class-and-namespace-rename. The `Workflow` is part of the environment, not just part of specific methods. Think of it like `System.Environment` or `System.Threading.ThreadPool`.
