### ISSUE TITLE
[Feature Request] Clarify documentation on the effect of specifying the `NonRetryableErrorTypes` as an empty list

### ISSUE THREAD

**Issue by eugbyte** [temporalio/sdk-dotnet#189]
### Is your feature request related to a problem? Please describe.

Per the [Temporal documentation](https://docs.temporal.io/retry-policies#default-behavior), workflows do not retry by default.

One may expect that by specifying that the `NonRetryableErrorTypes` as an empty list, the default behaviour is followed. However, specifying `NonRetryableErrorTypes` result in the workflow always retrying. My guess is that since all kinds of errors (including `ActivityFailureException` and `ApplicationFailureException`) are omitted from not retrying, the workflow will always retry.

`Client code:`
```
WorkflowOptions workflowOptions = new() {
    Id = workflowId,
    TaskQueue = EmailWorkflow.TaskQueueName,
    RetryPolicy = new() { NonRetryableErrorTypes = [] }, // <= the workflow always retry
};
var handle = await client.StartWorkflowAsync(
    workflowRunCall: (MyWorkflow wf) => wf.RunAsync(),
    options: workflowOptions);
```

`Workflow.cs:`
```
    [WorkflowRun]
    public async Task RunAsync() {
         throw new ApplicationFailureException(message: "some error", nonRetryable: true); // <= expects the workflow to not retry, but workflow retries
    }
```

When observing the dashboard via the [Temporal Web UI](https://learn.temporal.io/getting_started/typescript/dev_environment/#set-up-a-local-temporal-development-cluster-with-temporal-cli), the workflow is retried.
### Describe the solution you'd like

Clarify in the documentation that by specifying that the `NonRetryableErrorTypes` as an empty list, the Workflow will always be retried.

**Comment by cretz** [comment]
> One may expect that by specifying that the NonRetryableErrorTypes as an empty list, the default behaviour is followed [...] Clarify in the documentation that by specifying that the NonRetryableErrorTypes as an empty list, the Workflow will always be retried.

This is unrelated to `NonRetryableErrorTypes`. `null` is the default retry policy, but you are changing that default by providing a non-null value. And since you aren't setting any of the other retry policy values, those have defaults too. The documentation of `WorkflowOptions.RetryPolicy` mentions unset retry policy means no retry and the documentation of `RetryPolicy` mentions what the default values are of each property you don't set. But we can clarify more if this is surprising.

(closing as question, but feel free to continue commenting here or join us in the `#dotnet-sdk` channel on https://t.mp/slack or in the forums).
