### ISSUE TITLE
[Feature Request] Clarification of the release cycle

### ISSUE THREAD

**Issue by dpr-dev** [temporalio/sdk-dotnet#197]
### Is your feature request related to a problem? Please describe.

Hi all

Guys, thanks a lot for the .net sdk

Unfortunately, it's been about 3 months since the first version of the sdk was released in nuget,. Nevertheless, it can be seen that some useful fixes have been made (and work on .net sdk continues). Based on this, I have a quick question

Have you ever thought about describing the release cycle of .net sdk in some way ? This would help a lot in waiting for certain features or bug fixes. For example, this could be done with projects or milestones on github. 

What do you think about this ? 

Thank you

**Comment by cretz** [comment]
> Have you ever thought about describing the release cycle of .net sdk in some way ? This would help a lot in waiting for certain features or bug fixes.

We don't have a fixed release cycle since there are not enough changes to justify one (as there were for past SDKs where we were adding a lot of features). Therefore we try not to have public milestones to build expectations. Basically it'd just be a single "next" milestone with no specific time set which has no real value.

We tend to release as issues warrant. We will happily field requests to release sooner (here, or maybe even better, on [Slack](https://t.mp/slack) in the `#dotnet-sdk` channel).

**Comment by cretz** [comment]
(closing as question, but feel free to continue to discuss here or on Slack or wherever)
