### ISSUE TITLE
[Bug] samples-dotnet can not finish job.

### ISSUE THREAD

**Issue by charzhao** [temporalio/sdk-dotnet#35]
I try to run the example https://github.com/temporalio/samples-dotnet, but the job is always in running status. if i run the go "helloworld", the job can finish in time.

![image](https://user-images.githubusercontent.com/19890226/224266323-1cc08eb4-9da1-47e7-b388-089a938f8e16.png)

**Comment by cretz** [comment]
Did you follow the README at https://github.com/temporalio/samples-dotnet/tree/main/src/ActivityWorker? You have to run the Go worker. The sample is showing how Go and .NET work together since .NET workflows aren't developed yet. also, if you are having samples issues, feel free to open an issue there or if you have general questions or need help, join us on our forum at https://community.temporal.io/ or Slack `#dotnet-sdk` channel at https://t.mp/slack.

(closing as question, but you can continue to respond here)
